/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'SPI_LED_Driver_Project+Target_1' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "MG32x02z.h"

/* Megawin::ChipInit_Wizard:CSC@1.0.4 */
#define MG32x02z_ConfigerWizard_CSC
/* Megawin::ChipInit_Wizard:GPIO&LQFP80U@1.0.0 */
#define MG32x02z_Package_LQFP80         
        #define MG32x02z_ConfigerWizard_GPIO
        #define MG32x02z_GPIO_FILENAME  "MG32x02z_GPIO_LQFP80U_Init.h"
/* Megawin::Device:Startup@1.0.4 */
#define RTE_DEVICE_STARTUP_MG32F02U128    /* Device Startup for MG32F02U128 */
/* Megawin::Driver:Driver-All@1.0.1 */
#define IRQHandler_Driver_Level_


#endif /* RTE_COMPONENTS_H */
